on: [push]

jobs:
  get_spdx_licenses:
    name: get-spdx-licenses
    runs-on: ubuntu-latest
    steps:
      - name: Install TypeScript compiler
        run: npm install typescript
      - name: Install runtime dependencies
        run: npm install
      - name: Transpile TypeScript code into JavaScript code
        run: tsc
      - name: Get the list of licenses, print it here
        run: node build/get_spdx_licenses.js
