name: get-spdx-licenses

# Trigger this workflow by clicking the button in GitHub's web interface
on: workflow_dispatch

jobs:
  get_spdx_licenses:
    name: get-spdx-licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use latest LTS Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install TypeScript compiler
        run: npm install typescript

      - name: Install runtime dependencies
        run: npm install

      - name: Transpile TypeScript code into JavaScript code
        run: npm run build

      - name: Get the list of licenses, print it here
        run: node build/get_spdx_licenses.js | jq --indent 4 | sed 's/^/        /'
